module.exports={
  LOGIN:'LOGIN',
  TOKEN: 'TOKEN',
  LOGOUT: 'LOGOUT',
  GET_COURSE_SUMMARY: 'GET_COURSE_SUMMARY',
  GET_COURSE: 'GET_COURSE',
  GET_COURSE_PROJECT_LIST: 'GET_COURSE_PROJECT_LIST',
  GET_COURSE_ANNOUNCEMENT_LIST: 'GET_COURSE_ANNOUNCEMENT_LIST',
  GET_ATTENDED_COURSE: 'GET_ATTENDED_COURSE'
};